language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "4"
  - "5"
install:
  - npm install
script:
  - npm run release:production
after_success:
  - npm run cover:report-coverage
  - npm run docs:deploy
