language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '7'
- '6'
- '4'
before_install:
- openssl aes-256-cbc -K $encrypted_9413e5187502_key -iv $encrypted_9413e5187502_iv
  -in id_gh_pages_rsa.enc -out id_gh_pages_rsa -d
before_script:
- npm prune
script:
- npm run release:production
after_success:
- npm run cover:report-coverage
- npm run semantic-release
- npm run gh-pages-travis
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
  - gh-pages
env:
  global:
    - SSH_KEY="id_rsa"
    - GIT_NAME="Gleb Galkin"
    - GIT_EMAIL="gleb.galkin@zalando.de"
    - SOURCE_DIR="docs"
    - DEPLOY_BRANCH="master"
